# Generated by Django 3.1.7 on 2021-04-15 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConvoPreview',
            fields=[
                ('Group_Name', models.CharField(default='DEFAULT_GROUP', max_length=200)),
                ('Thumbnail', models.ImageField(default='/404.png', upload_to='uploads/')),
                ('GroupId', models.AutoField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('Message_Text', models.CharField(default='DEFAULT_MESSAGE', max_length=200)),
                ('Time_Stamp', models.DateField()),
                ('Author', models.CharField(default='DEFAULT_AUTHOR', max_length=200)),
                ('MessageId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('GroupConvo', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.SET_DEFAULT, to='social_app.convopreview')),
            ],
        ),
    ]
