# Generated by Django 3.1.7 on 2021-04-26 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConvoPreview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Group_Name', models.CharField(default='DEFAULT_GROUP', max_length=200)),
                ('Thumbnail', models.ImageField(default='/404.png', upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('password', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('Message_Text', models.CharField(default='DEFAULT_MESSAGE', max_length=200)),
                ('Time_Stamp', models.DateField()),
                ('MessageId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Author', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
                ('GroupConvo', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.SET_DEFAULT, to='social_app.convopreview')),
            ],
        ),
    ]
