# Generated by Django 3.1.7 on 2021-05-07 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='convopreview',
            name='Description',
            field=models.CharField(default='DEFAULT_DESCRIPTION', max_length=500),
        ),
    ]
