# Generated by Django 3.1.7 on 2021-04-29 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0002_auto_20210429_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwrapper',
            name='starredGroupConvos',
            field=models.ManyToManyField(default=-1, null=True, to='social_app.ConvoPreview'),
        ),
    ]
