# Generated by Django 3.1.7 on 2021-04-15 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0002_auto_20210415_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convopreview',
            name='Group_Name',
            field=models.CharField(default='DEFAULT_GROUP', max_length=200),
        ),
        migrations.AlterField(
            model_name='convopreview',
            name='Thumbnail',
            field=models.ImageField(default='/404.png', upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='Author',
            field=models.CharField(default='DEFAULT_AUTHRO', max_length=200),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='Message_Text',
            field=models.CharField(default='DEFAULT_MESSAGE', max_length=200),
        ),
    ]
